[
{"name":"Midnight Mirage", "artist":"Luna Vale","length":"3:42"},
{"name":"City Lights Fade", "artist":"Echo Season","length":"4:13"},
{"name":"Golden Sky", "artist":"The Jetsons","length":"2:56"},
{"name":"Whispers of You", "artist":"Isla Ray","length":"3:34"},
{"name":"Gravity's Hold", "artist":"Nova Theory","length":"5:01"},
{"name":"Sapphire Hearts", "artist":"Crystal Vibe","length":"3:28"},
{"name":"Time to Begin", "artist":"Miles Carter","length":"4:00"},
{"name":"Shadow Parade", "artist":"Fable District","length":"3:47"},
{"name":"Catch My Flame", "artist":"Hailey Knox","length":"2:59"},
{"name":"Above the Noise", "artist":"Zeke Lowell","length":"3:20"},
{"name":"No Tomorrow", "artist":"The Voltage","length":"3:51"},
{"name":"Echoes and Ashes", "artist":"Neon Reign","length":"4:27"},
{"name":"Dreamwire", "artist":"SynthNova","length":"3:03"},
{"name":"Hold Me in Static", "artist":"Verra James","length":"4:18"},
{"name":"River in the Sky", "artist":"Lily Ghost","length":"3:11"},
{"name":"Glass Wings", "artist":"Juno Pulse","length":"3:36"},
{"name":"End of the Frame", "artist":"Atlas Nine","length":"4:12"},
{"name":"Replay the Stars", "artist":"Kiera Dawn","length":"3:19"},
{"name":"Phantom Touch", "artist":"Remedy Drift","length":"4:04"},
{"name":"Neon Dust", "artist":"Electric Alibi","length":"3:50"},
{"name":"Feverline", "artist":"Cassette Hearts","length":"2:47"},
{"name":"Walk With Thunder", "artist":"Rogue Wren","length":"4:39"},
{"name":"Honey Collapse", "artist":"Summer Nightfall","length":"3:32"},
{"name":"Wild & Woven", "artist":"Mara Sloan","length":"4:07"},
{"name":"Lunar Lapse", "artist":"Orbit Sky","length":"3:14"},
{"name":"Crystalline Roads", "artist":"The Moonday Club","length":"5:12"},
{"name":"Voltage Bloom", "artist":"Fiction Atlas","length":"3:41"},
{"name":"Signs in the Fog", "artist":"Grey Hollow","length":"4:23"},
{"name":"Beneath the Frame", "artist":"Stella North","length":"3:17"},
{"name":"Flash and Fade", "artist":"Zayn Vireo","length":"2:54"},
{"name":"Ocean Circuit", "artist":"Niko Dash","length":"3:48"},
{"name":"Wake the Dream", "artist":"Velour Twin","length":"4:16"},
{"name":"Light & Linen", "artist":"Amber Echo","length":"3:29"},
{"name":"No Signal", "artist":"Delta Suns","length":"3:38"},
{"name":"Cotton Bloom", "artist":"Hazel Ridge","length":"4:05"},
{"name":"Pastel Screams", "artist":"Venna Mae","length":"3:22"},
{"name":"Black Velvet Dusk", "artist":"Orion Tailor","length":"3:58"},
{"name":"Rain Chaser", "artist":"Everlow","length":"4:10"},
{"name":"Broken Halos", "artist":"Myra Devine","length":"3:45"},
{"name":"Chrome Feathers", "artist":"Astro Cherry","length":"3:52"},
{"name":"Flicker and Burn", "artist":"Jordan Mars","length":"4:09"},
{"name":"Moonrider", "artist":"The Silver Flares","length":"4:00"},
{"name":"Caramel Static", "artist":"Tori Waves","length":"2:59"},
{"name":"Digital Lullaby", "artist":"Melody Run","length":"3:33"},
{"name":"Sunset Alchemy", "artist":"Cloud Ritual","length":"4:20"},
{"name":"Velvet Equation", "artist":"Sonya Blue","length":"3:26"},
{"name":"Last Light Lounge", "artist":"Echo Blue","length":"3:13"},
{"name":"Hollow Magic", "artist":"Flicker Frost","length":"3:44"},
{"name":"Rose Quartz Daydream", "artist":"Dusk Twins","length":"5:00"},
{"name":"Crush Code", "artist":"Ash Monroe","length":"3:10"},
{"name":"Drift Protocol", "artist":"Sage Eleven","length":"3:35"},
{"name":"Paper Constellations", "artist":"Jade Linden","length":"3:59"},
{"name":"Infinite Avenue", "artist":"Low Halo","length":"3:27"},
{"name":"Starblind Heart", "artist":"Cory Vane","length":"4:33"},
{"name":"Static Bloom", "artist":"Vin Vega","length":"3:02"},
{"name":"Open Flame", "artist":"Rhea Nash","length":"4:12"},
{"name":"Bittersweet Dawn", "artist":"Sienna Mars","length":"4:15"},
{"name":"Heartline Echo", "artist":"Lior Grace","length":"3:38"},
{"name":"Between Now and Blue", "artist":"Tristan North","length":"3:50"},
{"name":"Anthem of the Fall", "artist":"October Tide","length":"3:46"},
{"name":"Lightspeed Darling", "artist":"Nova Drift","length":"3:09"},
{"name":"Coldfire Sunset", "artist":"Astrid Bloom","length":"4:31"},
{"name":"Ivory Storm", "artist":"The Faint Lines","length":"3:25"},
{"name":"Violet Static", "artist":"The Sonar Kids","length":"3:36"},
{"name":"Cherry Bones", "artist":"Zoey Hyde","length":"3:40"},
{"name":"Blush Rain", "artist":"Meadowlane","length":"3:53"},
{"name":"Deep End City", "artist":"Echo Haze","length":"4:22"},
{"name":"Vanishing Point", "artist":"Jet Miles","length":"3:44"},
{"name":"Nightshade Blues", "artist":"Liam Roscoe","length":"3:31"},
{"name":"Caffeine Soul", "artist":"Ryder Knox","length":"3:18"},
{"name":"Starless Roads", "artist":"Astra Belle","length":"3:49"},
{"name":"Motionless Glow", "artist":"The Static Drift","length":"4:04"},
{"name":"Quiet Electricity", "artist":"Mythos State","length":"3:30"},
{"name":"Empty Neon", "artist":"Delilah Moons","length":"4:19"},
{"name":"Gleam & Grit", "artist":"Tommy Knave","length":"3:00"},
{"name":"Hearts at Altitude", "artist":"Runaway Comet","length":"3:42"},
{"name":"Through the Lens", "artist":"Indigo Choir","length":"3:55"},
{"name":"Signs of Silk", "artist":"Velva Hollow","length":"3:39"},
{"name":"Rescue Gravity", "artist":"Adler Stone","length":"4:25"},
{"name":"Satellite Summer", "artist":"The Miradors","length":"3:35"},
{"name":"Wild Static", "artist":"Lola East","length":"3:28"},
{"name":"Bronze Horizon", "artist":"Blake Elan","length":"3:47"},
{"name":"Orchid Fractals", "artist":"Juno Shade","length":"4:14"},
{"name":"High Voltage Moon", "artist":"Static Echoes","length":"3:50"},
{"name":"Twilight Remedy", "artist":"Ivy North","length":"3:45"},
{"name":"Beyond Fever", "artist":"Riot Aeon","length":"3:58"},
{"name":"Strange Chemistry", "artist":"Elle Velocity","length":"3:36"},
{"name":"Amber Hollow", "artist":"The Sunday Codes","length":"4:06"},
{"name":"Stardust Sirens", "artist":"Celeste Riot","length":"4:18"},
{"name":"Crushlight", "artist":"Brielle Skye","length":"3:43"},
{"name":"Paper Fireworks", "artist":"Tyler Voss","length":"3:31"},
{"name":"Miles Behind Mars", "artist":"Solar Bloom","length":"4:05"},
{"name":"Pulse & Petals", "artist":"June Holiday","length":"3:26"},
{"name":"Eclipse Parade", "artist":"The Ivory Frames","length":"4:10"},
{"name":"Static Velvet", "artist":"Flicker Noir","length":"3:49"},
{"name":"Blue Mist Revival", "artist":"Cass Wilder","length":"3:54"},
{"name":"Digital Garden", "artist":"Rain Summers","length":"4:01"},
{"name":"Candle Codes", "artist":"The Gold Vignettes","length":"3:20"},
{"name":"Parallel Silence", "artist":"Noah Vale","length":"4:30"}
]